apiVersion: v2
name: littlered
description: A Helm chart for deploying the LittleRed Redis operator
type: application
version: 0.4.0-rc1
appVersion: "latest"
home: https://github.com/chuck-chuck-chuck-net/littlered
sources:
  - https://github.com/chuck-chuck-chuck-net/littlered
maintainers:
  - name: chuck-chuck-chuck-net
